actions:
  'WARN':
    '3':
      action: 'GKICK'
      reason: 'You''ve received your %count%th warning!'
    '4':
      action: 'GTEMPBAN'
      duration: '7d'
      reason: 'You''ve received your %count%th warning!'
    '5':
      action: 'GTEMPBAN'
      duration: '2w'
      reason: 'You''ve received your %count%th warning!'
    '6':
      action: 'GTEMPBAN'
      duration: '1mo'
      reason: 'You''ve received your %count%th warning!'